name: release

on:
  push:
    tags:
      - v*

jobs:
  prepare:
    runs-on: ubuntu-18.04
    outputs:
      release: ${{ steps.info.outputs.name }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Prepare release info
      id: info
      env:
        TAG: ${{ github.ref }}
      run: python -c "print('::set-output name=name::' + '$TAG'.lstrip('refs/tags/'))"
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}

  mac-build:
    continue-on-error: true
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - name: noop
      run: echo hi
  
  homebrew-bump:
    needs: [prepare, mac-build]
    runs-on: ubuntu-latest
    steps:
      - uses: fanzeyi/bump-homebrew-formula-action@v1
        with:
          formula-name: watchman
          formula-path: watchman.rb
          homebrew-tap: fanzeyi/homebrew-fb
          base-branch: master
          download-url: https://github.com/facebook/watchman/releases/download/${{ needs.prepare.outputs.release }}/watchman-${{ needs.prepare.outputs.release }}-macos.zip
          commit-message: bump watchman to ${{ needs.prepare.outputs.release }}
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}